name: CI GitHub Actions

on:
  push:
    branches: [ "main", "feature/hola" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener codigo del repositorio
        uses: actions/checkout@v4

      - name: Ejecutar mensaje de prueba
        run: echo "¡El workflow de GitHub Actions se ha ejecutado correctamente!"