name: Calculadora de Suma con Python

on:
  push:
    branches: [ "main", "feature/hola" ]
  pull_request:
    branches: [ "main" ]

jobs:
  realizar_suma:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ejecutar script de suma en Python
        run: |
          python -c "
          num1 = 15
          num2 = 25
          resultado = num1 + num2
          print('----------------------------------------')
          print(f'El resultado de sumar {num1} + {num2} en Python es: {resultado}')
          print('----------------------------------------')
          "